title: Youth in Front
email: youthinfront@mit.edu
description: Youth In Front
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://youthinfront.org" # maybe?

# Build settings
markdown: kramdown
theme: minima
